<a href="https://colab.research.google.com/github/Kimiko00/GA-TSP/blob/main/GATSP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from array import *
import operator

In [ ]:
from google.colab import files
files.upload()

In [ ]:
# dataframe = pd.read_csv('berlin52.csv')
# daftarKota = dataframe.values.tolist()

# for i in daftarKota:
#   for j in i:
#     print(j, end=" ")
#   print()

# jumlahKota = len(daftarKota)
# print(jumlahKota)


daftarKota = [[20,2], [15,2], [35, 1], [40,1], [15,1], [15,1], [10,1]]
for i in daftarKota:
    for j in i:
        print(j,end = " ")
    print()

jumlahKota =  len(daftarKota)   
print(jumlahKota)

20 2 
15 2 
35 1 
40 1 
15 1 
15 1 
10 1 
7


In [ ]:
def initPopulasi(ukuranPopulasi,jumlahKota):
  P = np.empty((ukuranPopulasi,jumlahKota))
  P = P.astype('int')
  for i in range(ukuranPopulasi):
    I = np.random.permutation(jumlahKota)
    for j in range(jumlahKota):
      P[i][j]=I[j]
  return P


ukuranPopulasi = 20
P = initPopulasi (ukuranPopulasi,jumlahKota)
print(P)

[[0 4 6 1 2 5 3]
 [4 1 3 0 5 6 2]
 [4 0 2 1 6 3 5]
 [3 4 2 5 6 1 0]
 [2 6 5 0 3 4 1]
 [2 0 5 6 4 3 1]
 [0 4 1 3 2 5 6]
 [0 6 1 4 2 3 5]
 [5 3 6 0 1 4 2]
 [4 3 1 0 6 2 5]
 [2 5 0 4 3 1 6]
 [2 0 6 5 3 4 1]
 [0 1 6 4 3 5 2]
 [4 0 3 5 2 6 1]
 [6 1 5 2 3 4 0]
 [4 5 6 2 0 3 1]
 [0 3 1 2 5 6 4]
 [1 5 3 4 0 6 2]
 [4 5 1 3 0 6 2]
 [1 4 3 6 0 5 2]]


In [ ]:
def fungsiObjectif(populasi,daftarKota):
  sz = populasi.shape
  ukuranPopulasi = sz[0]
  jumlahKota = sz[1]

  matrikJarak = np.empty((ukuranPopulasi))
  matrikJarak  = matrikJarak.astype('float')
  n = len(daftarKota)

  for i in range(ukuranPopulasi):
    jarak = 0
    for j in range(n-1):
      jrkX = daftarKota[populasi[i][j]][0]-daftarKota[populasi[i][j+1]][0]
      jrkY = daftarKota[populasi[i][j]][1]-daftarKota[populasi[i][j+1]][1]
      d = np.sqrt(jrkX**2 + jrkY**2 )   
      jarak = jarak  + d
      
    dn =  np.sqrt((daftarKota[populasi[i][n-1]][0]-daftarKota[populasi[i][0]][0])**2+ (daftarKota[populasi[i][n-1]][1]-daftarKota[populasi[i][0]][1])**2 )
    jarak = jarak  + dn
    matrikJarak[i] = jarak

  return matrikJarak

fitP = fungsiObjectif(P,daftarKota)
print(fitP)

[100.24800782 101.14399591 100.2563198  100.12400391 101.1489883
 100.17729229  71.16888714  71.24791465 111.04987562 110.06986763
 110.31705055 101.10815639 100.13231589 101.22302342  71.24791465
  91.07827278 100.16898031 111.17387953 101.09485202 111.17387953]


In [ ]:
def seleksi (P,fsObj):
  jmlInduk = 2
  sz = P.shape
  ukuranPopulasi = sz[0]
  jumlahKota = sz[1]

  Induk = np.empty((jmlInduk,jumlahKota))
  Induk = Induk.astype('int')
  
  for i in range (2):
    # memilih dua individu secara acak 
    r1 = random.randint(0,ukuranPopulasi-1)
    r2 = random.randint(0,ukuranPopulasi-1)
    
    if  fsObj[r1] < fsObj [r2]:
      for j in range(jumlahKota):
        Induk [i][j] = P[r1][j]
    else:
      for j in range(jumlahKota):
        Induk [i][j] = P[r2][j]
  return Induk

Induk = seleksi(P,fitP)
print(Induk)

[[3 4 2 5 6 1 0]
 [2 0 6 5 3 4 1]]


In [ ]:
def PMX(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]
  #print(sz, brs, kol)

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  r1 = random.randint(1,kol-2)

  for i0 in range(r1): 

    Anak [0][i0] = Induk[0][i0]
    Anak [1][i0] = Induk[1][i0]

  batasCek1 = r1
  batasCek2 = r1

  for i in range(kol):
    m = (i+r1)%kol

    n1 = Induk[0][i] 
    n2 = Induk[1][i]

    #mengecek apakah kota tertentu sudah ada di anak
    idxAda1 = 0
    idxAda2 = 0
    for j1 in range(batasCek1): 
      
      if batasCek1>(kol-1):
        idxAda1 = 1

      if Anak [0][j1] ==n2: 
        idxAda1 = 1
            
    for j2 in range(batasCek2): 
      
      if batasCek2>(kol-1):
        idxAda2 = 1

      if Anak [1][i0]  == n1: 
        idxAda2 = 1

    if idxAda1 == 0:
      Anak[0][batasCek1] = n2
      batasCek1 = batasCek1 +1
   
    if idxAda2 == 0:
      Anak[1][batasCek2] = n1
      batasCek2 = batasCek2 +1
   
  return Anak

AnakCX = PMX(Induk)
print("Anak :",AnakCX)

Anak : [[3 2 0 6 5 4 1]
 [2 3 4 5 6 1 0]]


In [ ]:
def MutasiSwap(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  Anak = Induk

  r1 = random.randint(0,kol-1)
  r2 = random.randint(0,kol-1)

  while r1 == r2:
    r2 = random.randint(0,kol-1)

  I1rs1 = Induk [0][r1]
  I1rs2 = Induk [0][r2]
  I2rs1 = Induk [1][r1]
  I2rs2 = Induk [1][r2] 

  Anak [0][r1] = I1rs2
  Anak [0][r2] = I1rs1
  Anak [1][r1] = I2rs2  
  Anak [1][r2] = I2rs1

  return Anak

print("AnakCX :",AnakCX)
AnakM = MutasiSwap(AnakCX)
print("AnakM :",AnakM)

AnakCX : [[3 2 0 6 5 4 1]
 [2 3 4 5 6 1 0]]
AnakM : [[5 2 0 6 3 4 1]
 [6 3 4 5 2 1 0]]


In [ ]:
def Elitism(P,Anak,fitP,fitAnak):
  szP = P.shape
  brsP = szP[0]
  kolP = szP[1]
  szA = Anak.shape
  brsA = szA[0]
  kolA = szA[1]

  #print (fitP)
  for i in range(brsA):
    iJelek = fitP.max()
    idxJelek = fitP.argmax()

    if fitAnak[i]<iJelek:
      fitP[idxJelek] = fitAnak[i]
      for j in range (kolP):
        P[idxJelek][j] = Anak[i][j]

  return [P,fitP]

fitAnak= fungsiObjectif(AnakM,daftarKota)
print(P)
print(AnakM)
print(fitP)
print(fitAnak)
P = Elitism (P,AnakM,fitP,fitAnak)
print(P)
print(fitP)

[[0 4 6 1 2 5 3]
 [4 1 3 0 5 6 2]
 [4 0 2 1 6 3 5]
 [3 4 2 5 6 1 0]
 [2 6 5 0 3 4 1]
 [2 0 5 6 4 3 1]
 [0 4 1 3 2 5 6]
 [0 6 1 4 2 3 5]
 [5 3 6 0 1 4 2]
 [4 3 1 0 6 2 5]
 [2 5 0 4 3 1 6]
 [2 0 6 5 3 4 1]
 [0 1 6 4 3 5 2]
 [4 0 3 5 2 6 1]
 [6 1 5 2 3 4 0]
 [4 5 6 2 0 3 1]
 [0 3 1 2 5 6 4]
 [1 5 3 4 0 6 2]
 [4 5 1 3 0 6 2]
 [1 4 3 6 0 5 2]]
[[5 2 0 6 3 4 1]
 [6 3 4 5 2 1 0]]
[100.24800782 101.14399591 100.2563198  100.12400391 101.1489883
 100.17729229  71.16888714  71.24791465 111.04987562 110.06986763
 110.31705055 101.10815639 100.13231589 101.22302342  71.24791465
  91.07827278 100.16898031 111.17387953 101.09485202 111.17387953]
[102.083172   110.07486002]
[array([[0, 4, 6, 1, 2, 5, 3],
       [4, 1, 3, 0, 5, 6, 2],
       [4, 0, 2, 1, 6, 3, 5],
       [3, 4, 2, 5, 6, 1, 0],
       [2, 6, 5, 0, 3, 4, 1],
       [2, 0, 5, 6, 4, 3, 1],
       [0, 4, 1, 3, 2, 5, 6],
       [0, 6, 1, 4, 2, 3, 5],
       [5, 3, 6, 0, 1, 4, 2],
       [4, 3, 1, 0, 6, 2, 5],
       [2, 5, 0, 4, 3, 1, 6],
 

In [ ]:
# for run in range(2):
#   print("running ke -", run+1)
#   PCX = 0.6
#   Pm = 0.5
#   ukuranPopulasi = 10
#   max_generasi = 20

#   # Inisialisasi populasi 

#   P = initPopulasi (ukuranPopulasi,jumlahKota)
#   #print("P0 :",P)

#   #melakukan evaluasi P
#   fitP = fungsiObjectif(P,daftarKota)
#   print("fitness populasi awal:",fitP)

#   print("fitness terbaik awal:",fitP.min())
#   print("rute awal :",P[fitP.argmin()])


#   for i in range(max_generasi):
#     #print("generasi :",i)
#     Induk = seleksi(P,fitP)
#     #print("Induk :",Induk)

#     Anak = Induk

#     rxo = random.random()

#     if rxo < PCX:
#       Anak = PMX(Induk)
#       #print("AnakXO :",Anak)

#       rm = random.random()
#       if rm < Pm:
#         Anak = MutasiSwap(Anak)
#         #print("AnakR :",Anak)

#     fitAnak = fungsiObjectif(Anak,daftarKota)
#     #print("fitAnak :",fitAnak)

#     #print("fitness:",fitAnak.min())

#     [P, fitP] = Elitism (P,Anak,fitP,fitAnak)    
#   print("fitness populasi akhir:",fitP)
#   print("fitness akhir:",fitP.min())
#   print("rute akhir :",P[fitP.argmin()])

# Inisialisasi paramater
PCX = 0.7
Pm = 0.01
ukuranPopulasi = 20
max_generasi = 500

# Inisialisasi populasi 

P = initPopulasi (ukuranPopulasi,jumlahKota)
print("P0 :",P)

#melakukan evaluasi P
fitP = fungsiObjectif(P,daftarKota)
print("fitness populasi awal:",fitP)

print("fitness terbaik awal:",fitP.min())
print("rute awal :",P[fitP.argmin()])


for i in range(max_generasi):
  #print("generasi :",i)
  Induk = seleksi(P,fitP)
  #print("Induk :",Induk)

  Anak = Induk

  rxo = random.random()

  if rxo < PCX:
    Anak = PMX(Induk)
    #print("AnakXO :",Anak)

    rm = random.random()
    if rm < Pm:
      Anak = MutasiSwap(Anak)
      #print("AnakR :",Anak)

  fitAnak = fungsiObjectif(Anak,daftarKota)
  #print("fitAnak :",fitAnak)

  #print("fitness:",fitAnak.min())

  [P, fitP]= Elitism (P,Anak,fitP,fitAnak)   
  
print("fitness populasi akhir:",fitP)
print("fitness akhir:",fitP.min())
print("rute akhir :",P[fitP.argmin()])

P0 : [[6 0 1 2 3 5 4]
 [5 4 0 2 3 6 1]
 [6 5 2 4 0 1 3]
 [2 1 6 5 4 0 3]
 [2 1 4 5 3 6 0]
 [1 2 0 4 6 3 5]
 [5 0 2 1 6 3 4]
 [0 3 2 4 5 1 6]
 [4 1 2 6 3 0 5]
 [5 2 1 3 0 6 4]
 [6 3 5 4 2 1 0]
 [5 4 2 0 6 1 3]
 [5 3 2 1 0 6 4]
 [3 6 4 1 5 0 2]
 [4 2 1 0 3 6 5]
 [0 6 1 5 3 4 2]
 [5 2 6 3 0 1 4]
 [0 6 3 2 1 5 4]
 [6 5 0 4 1 3 2]
 [0 2 6 4 5 1 3]]
fitness populasi awal: [ 70.07486002  61.23133541 110.11901152  60.24800782 101.10815639
 101.15730029 100.2563198   61.17387953 101.1489883  100.11983642
 110.07486002 100.20218352  70.07486002  62.13231589 100.04996879
 101.18219151 101.02498439  71.17387953  71.21803103  91.07827278]
fitness terbaik awal: 60.24800781618714
rute awal : [2 1 6 5 4 0 3]
fitness populasi akhir: [50.12400391 50.12400391 50.12400391 50.12400391 50.12400391 50.12400391
 50.12400391 50.12400391 50.12400391 50.12400391 50.12400391 50.12400391
 50.12400391 50.12400391 50.12400391 50.12400391 50.12400391 50.12400391
 50.12400391 50.12400391]
fitness akhir: 50.12400390809